# Telegram bot token
BotToken = "000000000:abcdefghijklmnopqrstuvwxyz123456789"

# Webhook listening port
# can be 443, 80, 88, 8443, assuming that ReverseProxy has been set to false
Port = 88

# Assert that this bot will be run behind a reverse proxy.
# This means that Port can be whatever you want (not only what Telegram says),
# and that IP will be 127.0.0.1, even if not specified.
ReverseProxy = false

# Port where this bot will listen, on the reverse proxy side
ReverseProxyPort = 1234

# IP to bind on
IP = "127.0.0.1"

# Domain where Telegram will send updates
Domain = "https://shitposting.io"

# Assert that the webhook webserver will use TLS
TLS = false

# TLS certificate path
TLSCertPath = "/path/to/the/tls/certificate"

# TLS key path
TLSKeyPath = "/path/to/the/tls/key"
